export {default as Navbar} from './Navbar/Navbar';
export {default as Footer} from './Footer/Footer';
export {default as Services} from './Services/Services';
export {default as Mission} from './Mission/Mission';
export {default as Feedbacks} from './Feedbacks/Feedbacks';
export {default as Home_part_med} from './Home_part_med/Home_part_med';
export {default as Doctors} from './Doctors/Doctors';
export {default as Fields} from './Fields/Fields';
export {default as Partners_desc} from './Partners_desc/Partners_desc';
export {default as Header} from './Header/Header';
export {default as Stories} from './Stories/Stories';
export {default as Success} from './Success/Success';
export {default as Tunisia} from './Tunisia/Tunisia';
export {default as Guide} from './Guide/Guide';
export {default as Procedure} from './Procedure/Procedure';
export {default as Sights_one} from './Sights_one/Sights_one';
export {default as Kairouan} from './Kairouan/Kairouan';
export {default as Multi_Religion} from './Multi_Religion/Multi_Religion';
export {default as Capital} from './Capital/Capital';
export {default as Hospitals} from './Hospitals/Hospitals';
export {default as Contact} from './Contact/Contact';
export {default as About_Desc} from "./About_Desc/About_Desc";
export {default as Chose} from './Chose/Chose';
export {default as Team} from './Team/Team';
export {default as Tataouine} from './Tataouine/Tataouine';
export {default as SidiBou} from './SidiBou/SidiBou';
export {default as Bizerte} from './Bizerte/Bizerte';
export {default as Form} from './Form/Form';
export {default as Message} from './Message/Message';
export {default as Dashboard} from './Dashboard/Dashboard'
export {default as Posted} from './Posted/Posted'
export {default as Post} from './Post/Post'
export {default as Esth_spec} from './Esth_spec/Esth_spec'
export {default as FormEs} from './FromEs/FormEs'
export {default as Devis} from './Devis/Devis'